# Generated by Django 5.2.6 on 2026-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
