# Generated by Django 5.2.6 on 2026-07-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_assigned_tutors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePathSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_sequential', models.BooleanField(default=False, help_text='Force students to complete lessons in sequence')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='path_settings', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('scorm', 'SCORM 1.2 Package'), ('h5p', 'H5P Package'), ('h5p_embed', 'H5P Embed URL')], max_length=15)),
                ('package_file', models.FileField(blank=True, help_text='SCORM or H5P zip/package file', null=True, upload_to='interactive_packages/')),
                ('embed_url', models.URLField(blank=True, help_text='For H5P iframe embed links', null=True)),
                ('launch_path', models.CharField(blank=True, help_text='SCORM entry point (e.g. index.html or path from manifest)', max_length=255, null=True)),
                ('extracted_dir', models.CharField(blank=True, help_text='Relative directory where package is extracted', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_content', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'prerequisite_course')},
            },
        ),
        migrations.CreateModel(
            name='LessonPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.lesson')),
                ('prerequisite_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'prerequisite_lesson')},
            },
        ),
    ]
