import json
import logging
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from openai import OpenAI

from ai_tools.models import AIRequestLog, AIUsageLimit, AISafetyFlag, AIMessage
from ai_tools.services.schemas import validate_json_structure
from ai_tools.services.prompts import clean_pii_from_text

logger = logging.getLogger(__name__)

# Fallbacks for schemas when API is unavailable/fails
FALLBACK_PRACTICE_QUESTIONS = {
    "questions": [
        {
            "question_text": "What is the primary topic of the lesson content?",
            "question_type": "objective",
            "options": ["The core concept", "An unrelated idea", "A random fact", "None of the above"],
            "correct_answer": "The core concept",
            "explanation": "Please refer back to the main lesson text for verification.",
            "difficulty": "medium"
        }
    ]
}

FALLBACK_QUIZ_DRAFT = {
    "title": "Practice Quiz Draft (Fallback)",
    "instructions": "Read each question carefully and select the best option.",
    "questions": [
        {
            "question_text": "Based on the lesson material, which of the following is correct?",
            "choices": ["Option A (Correct)", "Option B", "Option C", "Option D"],
            "correct_choice": "Option A (Correct)",
            "explanation": "This is a placeholder question generated by the fallback system.",
            "mark": 1
        }
    ]
}

FALLBACK_WORKSHEET = {
    "title": "Lesson Worksheet Draft (Fallback)",
    "instructions": "Write your answers in the spaces provided.",
    "sections": [
        {
            "heading": "Section A: Comprehension",
            "questions": [
                "Summarize the main topic of the lesson.",
                "Detail how the concepts in this lesson can be applied in daily life."
            ]
        }
    ],
    "answer_guide": "Tutor guide: Verify that the student has read the core text and understands the main points."
}

FALLBACK_REPORT_COMMENT = {
    "summary": "The student has made progress but requires consistent review.",
    "strengths": "Demonstrates focus and completes lesson readings.",
    "areas_for_improvement": "Needs to spend more time practicing mock exercises.",
    "recommendation": "Review lessons weekly and attempt all quizzes.",
    "tutor_comment": "Draft Comment: The student has shown dedication in reviewing course lessons. Focus should now shift toward improving assessment performance through practice."
}

FALLBACK_STUDY_PLAN = {
    "weak_areas": ["Recent lesson topics requiring revision"],
    "recommended_lessons": ["Review completed lessons"],
    "practice_tasks": ["Complete mock exercises at the end of the lesson"],
    "guardian_support_tip": "Provide a quiet study space and monitor weekly lesson completion.",
    "weekly_plan": [
        "Day 1-2: Review current week's lessons.",
        "Day 3-4: Attempt practice questions and worksheets.",
        "Day 5-7: Check for understanding and discuss with tutor."
    ]
}


def get_openai_client():
    """
    Returns OpenAI client using settings.OPENAI_API_KEY.
    Raises ValueError if API Key is not configured.
    """
    key = getattr(settings, 'OPENAI_API_KEY', '')
    if not key or key == 'mock-api-key-for-testing':
        raise ValueError("OpenAI API key is not configured or placeholder used.")
    return OpenAI(api_key=key)


def moderate_text(text, user=None):
    """
    Checks text safety using OpenAI Moderation API.
    Returns safe/flagged/categories breakdown.
    Handles API failure safely.
    """
    result = {
        "safe": True,
        "flagged": False,
        "categories": {},
        "raw": {}
    }
    
    if not getattr(settings, 'AI_REQUIRE_MODERATION', True):
        return result

    try:
        client = get_openai_client()
        response = client.moderations.create(
            input=text,
            model=getattr(settings, 'OPENAI_MODERATION_MODEL', 'omni-moderation-latest')
        )
        res_data = response.results[0]
        result["flagged"] = res_data.flagged
        result["safe"] = not res_data.flagged
        result["categories"] = {cat: val for cat, val in res_data.categories.__dict__.items()}
        result["raw"] = response.model_dump()
    except Exception as e:
        logger.error(f"Moderation API check failed: {e}")
        # Default to safe if API fails to avoid breaking user flow
        result["safe"] = True
        result["flagged"] = False
        
    return result


def increment_ai_usage(user, tokens_input=0, tokens_output=0):
    """
    Increments the daily AI request and token usage counters for a user.
    """
    today = timezone.localdate()
    limit_obj, created = AIUsageLimit.objects.get_or_create(
        user=user,
        date=today,
        defaults={'requests_count': 0, 'tokens_used': 0}
    )
    limit_obj.requests_count += 1
    limit_obj.tokens_used += (tokens_input + tokens_output)
    limit_obj.save()
    return limit_obj


def user_can_use_ai(user):
    """
    Returns True if user has not reached their daily AI limit.
    Staff/superusers are always allowed.
    """
    if not user or not user.is_authenticated:
        return False
        
    if user.is_staff or user.is_superuser:
        return True
        
    role = 'student'
    if hasattr(user, 'profile'):
        role = user.profile.role
        
    if role == 'admin':
        return True

    today = timezone.localdate()
    usage = AIUsageLimit.objects.filter(user=user, date=today).first()
    requests_today = usage.requests_count if usage else 0

    if role == 'tutor':
        limit = getattr(settings, 'AI_DAILY_TUTOR_LIMIT', 100)
        return requests_today < limit
    else:
        # student/guardian/other
        limit = getattr(settings, 'AI_DAILY_STUDENT_LIMIT', 30)
        return requests_today < limit


def generate_ai_response(prompt, system_instruction, user=None, context=None, request_type="general"):
    """
    Generates a text completion response from OpenAI.
    Enforces features active flags, limits, input/output moderation, request logs, and safety flags.
    """
    fallback_response = "I am currently having trouble connecting to the AI assistant. Please try again in a few moments or consult your tutor."
    prompt = clean_pii_from_text(prompt)
    
    if not getattr(settings, 'AI_FEATURES_ENABLED', True):
        return fallback_response, {"status": "disabled"}

    if user and not user_can_use_ai(user):
        return "You have reached your daily AI usage limit. Please try again tomorrow.", {"status": "limit_exceeded"}

    # Extract optional course/lesson context
    course = None
    lesson = None
    if context:
        course = context.get('course')
        lesson = context.get('lesson')

    # Moderation of User Input
    if getattr(settings, 'AI_REQUIRE_MODERATION', True):
        mod_result = moderate_text(prompt, user=user)
        if mod_result["flagged"]:
            # Log blocked request
            log = AIRequestLog.objects.create(
                user=user,
                request_type=request_type,
                course=course,
                lesson=lesson,
                prompt=prompt,
                response="Blocked due to input moderation flag.",
                status="blocked",
                model_used=getattr(settings, 'OPENAI_MODEL', 'gpt-4o-mini')
            )
            # Create safety flag
            AISafetyFlag.objects.create(
                user=user,
                request_log=log,
                flag_type="input_moderation",
                severity="high",
                description=f"User prompt triggered moderation: {json.dumps(mod_result['categories'])}"
            )
            return "Your prompt was flagged as inappropriate and has been blocked.", {"status": "blocked"}

    try:
        client = get_openai_client()
        messages = [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": prompt}
        ]
        
        model_name = getattr(settings, 'OPENAI_MODEL', 'gpt-4o-mini')
        response = client.chat.completions.create(
            model=model_name,
            messages=messages,
            temperature=0.7
        )
        
        output_text = response.choices[0].message.content or ""
        tokens_in = response.usage.prompt_tokens if response.usage else 0
        tokens_out = response.usage.completion_tokens if response.usage else 0
        
        # Moderation of AI Output
        if getattr(settings, 'AI_REQUIRE_MODERATION', True):
            out_mod = moderate_text(output_text, user=user)
            if out_mod["flagged"]:
                log = AIRequestLog.objects.create(
                    user=user,
                    request_type=request_type,
                    course=course,
                    lesson=lesson,
                    prompt=prompt,
                    response="Blocked due to output moderation flag.",
                    status="flagged",
                    model_used=model_name,
                    tokens_input=tokens_in,
                    tokens_output=tokens_out
                )
                AISafetyFlag.objects.create(
                    user=user,
                    request_log=log,
                    flag_type="output_moderation",
                    severity="medium",
                    description="AI response triggered moderation categories."
                )
                return "The AI generated response was flagged as unsafe. Please try rephrasing your request.", {"status": "flagged"}

        # Success Log
        log = AIRequestLog.objects.create(
            user=user,
            request_type=request_type,
            course=course,
            lesson=lesson,
            prompt=prompt,
            response=output_text,
            status="success",
            model_used=model_name,
            tokens_input=tokens_in,
            tokens_output=tokens_out
        )
        if user:
            increment_ai_usage(user, tokens_input=tokens_in, tokens_output=tokens_out)
            
        return output_text, {
            "status": "success",
            "tokens_input": tokens_in,
            "tokens_output": tokens_out,
            "model_used": model_name
        }

    except Exception as e:
        logger.error(f"OpenAI API request failure: {e}")
        # Log failure
        AIRequestLog.objects.create(
            user=user,
            request_type=request_type,
            course=course,
            lesson=lesson,
            prompt=prompt,
            response="",
            status="failed",
            error_message=str(e),
            model_used=getattr(settings, 'OPENAI_MODEL', 'gpt-4o-mini')
        )
        return fallback_response, {"status": "failed", "error": str(e)}


def generate_structured_ai_response(prompt, system_instruction, schema, user=None, context=None, request_type="structured"):
    """
    Generates a structured JSON response from OpenAI matching the schema.
    If API fails, returns a valid matching fallback dictionary.
    """
    prompt = clean_pii_from_text(prompt)
    if not getattr(settings, 'AI_FEATURES_ENABLED', True):
        return get_fallback_for_schema(schema), {"status": "disabled"}

    if user and not user_can_use_ai(user):
        return get_fallback_for_schema(schema), {"status": "limit_exceeded"}

    course = None
    lesson = None
    if context:
        course = context.get('course')
        lesson = context.get('lesson')

    # Moderation of input
    if getattr(settings, 'AI_REQUIRE_MODERATION', True):
        mod_result = moderate_text(prompt, user=user)
        if mod_result["flagged"]:
            log = AIRequestLog.objects.create(
                user=user,
                request_type=request_type,
                course=course,
                lesson=lesson,
                prompt=prompt,
                response="Blocked due to input moderation flag.",
                status="blocked",
                model_used=getattr(settings, 'OPENAI_MODEL', 'gpt-4o-mini')
            )
            AISafetyFlag.objects.create(
                user=user,
                request_log=log,
                flag_type="input_moderation",
                severity="high",
                description=f"Structured input triggered moderation: {json.dumps(mod_result['categories'])}"
            )
            return get_fallback_for_schema(schema), {"status": "blocked"}

    try:
        client = get_openai_client()
        messages = [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": prompt}
        ]
        model_name = getattr(settings, 'OPENAI_MODEL', 'gpt-4o-mini')
        
        # Request JSON mode response
        response = client.chat.completions.create(
            model=model_name,
            messages=messages,
            response_format={"type": "json_object"},
            temperature=0.7
        )
        
        output_text = response.choices[0].message.content or ""
        tokens_in = response.usage.prompt_tokens if response.usage else 0
        tokens_out = response.usage.completion_tokens if response.usage else 0
        
        try:
            parsed_json = json.loads(output_text)
        except Exception:
            raise ValueError("Response output is not valid JSON.")

        # Validate JSON structure
        if not validate_json_structure(parsed_json, schema):
            raise ValueError("Response JSON does not match the expected schema properties.")

        # Success Log
        AIRequestLog.objects.create(
            user=user,
            request_type=request_type,
            course=course,
            lesson=lesson,
            prompt=prompt,
            response=output_text,
            status="success",
            model_used=model_name,
            tokens_input=tokens_in,
            tokens_output=tokens_out
        )
        if user:
            increment_ai_usage(user, tokens_input=tokens_in, tokens_output=tokens_out)
            
        return parsed_json, {
            "status": "success",
            "tokens_input": tokens_in,
            "tokens_output": tokens_out,
            "model_used": model_name
        }

    except Exception as e:
        logger.error(f"OpenAI Structured Request Failure: {e}")
        # Log failure
        AIRequestLog.objects.create(
            user=user,
            request_type=request_type,
            course=course,
            lesson=lesson,
            prompt=prompt,
            response="",
            status="failed",
            error_message=str(e),
            model_used=getattr(settings, 'OPENAI_MODEL', 'gpt-4o-mini')
        )
        return get_fallback_for_schema(schema), {"status": "failed", "error": str(e)}


def get_fallback_for_schema(schema):
    """
    Returns the appropriate fallback dictionary for a given schema.
    """
    from ai_tools.services.schemas import (
        PRACTICE_QUESTIONS_SCHEMA, QUIZ_DRAFT_SCHEMA,
        WORKSHEET_SCHEMA, REPORT_COMMENT_SCHEMA, STUDY_PLAN_SCHEMA
    )
    if schema == PRACTICE_QUESTIONS_SCHEMA:
        return FALLBACK_PRACTICE_QUESTIONS
    elif schema == QUIZ_DRAFT_SCHEMA:
        return FALLBACK_QUIZ_DRAFT
    elif schema == WORKSHEET_SCHEMA:
        return FALLBACK_WORKSHEET
    elif schema == REPORT_COMMENT_SCHEMA:
        return FALLBACK_REPORT_COMMENT
    elif schema == STUDY_PLAN_SCHEMA:
        return FALLBACK_STUDY_PLAN
    return {}
